services:
  - type: web
    name: agentix-backend
    env: python
    plan: free
    autoDeploy: true
    region: oregon

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
