services:
  - type: web
    name: fastapi-backend
    env: python
    region: oregon  # Optional: closest to you for faster deploys
    plan: free
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Backend.main:app --host 0.0.0.0 --port $PORT  # <-- Matches your folder structure
